version: '3.9'
services:
    # Database
    mysql:
        container_name: mysql
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: "${DB_NAME}"
            MYSQL_USER: "${DB_USER}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci'
            ]
        ports:
            - 3306
        volumes:
            - db_data:/var/lib/mysql
            - ./db_dump:/docker-entrypoint-initdb.d
        networks:
          - wp-network

    # Wordpress
    wordpress:
        container_name: wordpress
        image: wordpress:php7.4-fpm-alpine
        restart: always
        stdin_open: true
        tty: true
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: "${DB_USER}"
            WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
            WORDPRESS_DB_NAME: "${DB_NAME}"
        volumes:
            - ./public_html:/var/www/html
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
          - wp-network

    # Webserver
    caddy:
      image: caddy
      container_name: caddy
      ports:
        - 80:80
        - 443:443
      volumes:
        - ./public_html:/var/www/html
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
      networks:
        - wp-network

networks:
  wp-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  db_data:
