version: '3.9'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 80

  wordpress:
    depends_on:
      - mysql
    image: wordpress:php7.4-fpm
    ports:
      - 9000
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php_extras.ini:/usr/local/etc/php/conf.d/php_extras.ini

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      WP_DOMAIN: "${WP_DOMAIN}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./wordpress:/var/www/html

volumes:
  caddy_config: {}
  caddy_data: {}
