services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: "${DB_PORT}"
      PMA_ARBITRARY: 1
    ports:
      - 80

  wordpress:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}:${DB_PORT}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    ports:
      - 9000
    volumes:
      - ./wordpress:/var/www/html
      - ./php/php_extras.ini:/usr/local/etc/php/conf.d/php_extras.ini
    depends_on:
      - mysql

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    environment:
      WP_DOMAIN: "${WP_DOMAIN}"
      DB_DOMAIN: "${DB_DOMAIN}"
      IP_WHITELIST: "${IP_WHITELIST}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./wordpress:/var/www/html

volumes:
  caddy_config:
  caddy_data:
